**1 - np.array() → Listeyi veya diziyi NumPy dizisine dönüştürür.**

Açıklama: NumPy dizileri, Python listelerinden daha hızlı ve verimli hesaplamalar yapmamızı sağlar.

In [1]:
import numpy as np

liste = [1, 2, 3, 4, 5]
dizi = np.array(liste)

dizi

array([1, 2, 3, 4, 5])

**2 - np.arange() → Belirtilen aralıktaki sayılarla NumPy dizisi oluşturur.**

Açıklama: range() fonksiyonuna benzer şekilde çalışır ancak NumPy dizisi döndürür.

In [2]:
dizi = np.arange(0, 10, 2)  # 0'dan 10'a kadar 2'şer artan dizi
dizi

array([0, 2, 4, 6, 8])

**3 - np.linspace() → Belirtilen aralıktaki sayıları eşit aralıklarla böler.**

Açıklama: start ve stop arasında eşit aralıklı n sayı üretir.

In [3]:
dizi = np.linspace(0, 5, 10)  # 0 ile 5 arasında 10 eşit parça oluşturur
dizi

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**4 - np.zeros() → Belirtilen boyutta sıfırlarla dolu bir dizi oluşturur.**

Açıklama: Genellikle matris ve tensör işlemlerinde başlangıç verisi olarak kullanılır.

In [4]:
matris = np.zeros((3, 4))  # 3 satır, 4 sütundan oluşan sıfır matrisi
matris

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**5 - np.ones() → Belirtilen boyutta birlerle dolu bir dizi oluşturur.**

Açıklama: np.zeros() fonksiyonuna benzer şekilde, başlangıç verisi olarak kullanılır.

In [5]:
matris = np.ones((2, 3))  # 2x3 boyutunda bir matrisi birlerle doldurur
matris

array([[1., 1., 1.],
       [1., 1., 1.]])

**6 - np.random.rand() → 0 ile 1 arasında rastgele sayılar üretir.**

Açıklama: Tek boyutlu veya çok boyutlu rastgele sayı dizileri oluşturur.


In [6]:
rastgele_dizi = np.random.rand(3, 3)  # 3x3'lük rastgele sayılar matrisi
rastgele_dizi

array([[0.64254359, 0.34995561, 0.33716739],
       [0.85303709, 0.20750412, 0.48479005],
       [0.87902143, 0.80273688, 0.75411625]])

**7 - np.reshape() → Dizinin şeklini değiştirir.**

Açıklama: Dizi eleman sayısı sabit kalırken, dizinin satır-sütun yapısını değiştirir.

In [10]:
dizi = np.arange(12)  # [0 1 2 ... 11]
yeni_dizi = dizi.reshape(3, 4)  # 3 satır, 4 sütunluk hale getirir
yeni_dizi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**8 - np.sum() → Dizideki elemanların toplamını alır.**

Açıklama: Belirtilen eksene göre toplama işlemi yapabilir.

In [14]:
matris = np.array([[1, 2, 3], [4, 5, 6]])
toplam = np.sum(matris)  # Tüm elemanların toplamı

satir_toplamları = np.sum(matris, axis=1)  # Her satırın toplamı

sutun_toplamları = np.sum(matris, axis=0)  # Her sütundaki toplam

print(f'Toplam: {toplam}')
print(f'Satır Toplamları: {satir_toplamları}')
print(f'Sütun Toplamları: {sutun_toplamları}')

Toplam: 21
Satır Toplamları: [ 6 15]
Sütun Toplamları: [5 7 9]


**9 - np.mean() → Ortalamayı hesaplar.**

Açıklama: Dizinin genel veya belirli bir eksendeki ortalamasını döndürür.

In [17]:
dizi = np.array([10, 20, 30, 40])
ortalama = np.mean(dizi)  # Dizinin ortalaması
print(f'ortalama:{ortalama}')

ortalama:25.0


**10 - np.argmax() & np.argmin() → Maksimum ve minimum elemanın indeksini döndürür.**

Açıklama: Büyük veri setlerinde maksimum/minimum değerlerin nerede olduğunu bulmak için kullanılır.

In [19]:
dizi = np.array([3, 7, 2, 9, 5])
print(f'En büyük elemanın indeksi:{np.argmax(dizi)}')
print(f'En küçük elemanın indeksi:{np.argmin(dizi)}')

En büyük elemanın indeksi:3
En küçük elemanın indeksi:2
